readonly: true

database:
  file:
    folder: "dev/local_db"
    extension: "json"

schemas:
  panels_path: "schemas/panels"
  queries_path: "schemas/queries"
  datasources_path: "schemas/datasources"
  variables_path: "schemas/variables"
  interval: "5m"

important_dashboards:
  - project: "perses"
    dashboard: "Demo"
  - project: "testing"
    dashboard: "DuplicatePanels"
  - project: "Unknown"
    dashboard: "Dashboard"

information: |-
  # Hello World
  ## File Database setup