security:
  readonly: false
  activate_permission: true
  encryption_key: "=tW$56zytgB&3jN2E%7-+qrGZE?v6LCc"
  authorization:
    activate_cache: true
    interval: 10m
    guest_permissions:
      - actions:
          - read
        scopes:
          - Dashboard
          - Datasource
          - Folder
          - GlobalDatasource
          - GlobalRole
          - GlobalRoleBinding
          - GlobalSecret
          - GlobalVariable
          - Project
          - Role
          - RoleBinding
          - Secret
          - User
          - Variable
      - actions:
          - create
        scopes:
          - Project

database:
  file:
    folder: "dev/local_db"
    extension: "json"

provisioning:
  folders:
  - "dev/data"

schemas:
  panels_path: "schemas/panels"
  queries_path: "schemas/queries"
  datasources_path: "schemas/datasources"
  variables_path: "schemas/variables"
  interval: "5m"

important_dashboards:
  - project: "perses"
    dashboard: "Demo"
  - project: "testing"
    dashboard: "DuplicatePanels"
  - project: "Unknown"
    dashboard: "Dashboard"

information: |-
  # Hello World
  ## File Database setup
