security:
  readonly: false
  encryption_key: "=tW$56zytgB&3jN2E%7-+qrGZE?v6LCc"
  authorization:
    enable_authorization: true
    enable_cache: true
    interval: 10m
    guest_permissions:
      - actions:
          - read
        scopes:
          - Dashboard
          - Datasource
          - Folder
          - GlobalDatasource
          - GlobalRole
          - GlobalRoleBinding
          - GlobalSecret
          - GlobalVariable
          - Project
          - Role
          - RoleBinding
          - Secret
          - User
          - Variable
      - actions:
          - create
        scopes:
          - Project

database:
  sql:
    user: "user"
    password: "password"
    db_name: "perses"
    net: "tcp"
    addr: "localhost:3306"
    allow_native_passwords: true

provisioning:
  folders:
    - "dev/data"

schemas:
  panels_path: "schemas/panels"
  queries_path: "schemas/queries"
  datasources_path: "schemas/datasources"
  variables_path: "schemas/variables"
  interval: "5m"

important_dashboards:
  - project: "perses"
    dashboard: "Demo"
  - project: "testing"
    dashboard: "DuplicatePanels"
  - project: "Unknown"
    dashboard: "Dashboard"

information: |-
  # Hello World
  ## MariaDB Database setup
