security:
  readonly: false
  encryption_key: "=tW$56zytgB&3jN2E%7-+qrGZE?v6LCc"
  enable_auth: true
  authorization:
    guest_permissions:
      - actions:
          - read
        scopes:
          - "*"
      - actions:
          - create
        scopes:
          - Project
  authentication:
    providers:
      enable_native: true
database:
  sql:
    user: "user"
    password: "password"
    db_name: "perses"
    net: "tcp"
    addr: "localhost:3306"
    allow_native_passwords: true

provisioning:
  folders:
    - "dev/data"

schemas:
  panels_path: "cue/schemas/panels"
  queries_path: "cue/schemas/queries"
  datasources_path: "cue/schemas/datasources"
  variables_path: "cue/schemas/variables"
  interval: "5m"

important_dashboards:
  - project: "perses"
    dashboard: "Demo"
  - project: "testing"
    dashboard: "DuplicatePanels"
  - project: "Unknown"
    dashboard: "Dashboard"

information: |-
  # Hello World
  ## MariaDB Database setup
