name: e2e
on:
  push:
    branches:
      - main
      - release/*
      # Do not run e2e tests on snapshots because they can be used for testing
      # WIP changes and are never intended to be merged into `main` or released.
    tags:
      - v*
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref_name != 'main' }}

jobs:
  e2e:
    name: end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - uses: perses/github-actions@v0.11.0
      - uses: ./.github/perses-ci/actions/setup_environment
        with:
          enable_npm: true
          enable_go: true
          nvmrc_path: "./ui/.nvmrc"
      - name: Install UI deps
        working-directory: ./ui
        run: npm ci
      - name: Build the app and all packages
        working-directory: ./ui
        run: npm run build
      - name: Install Playwright Browsers
        working-directory: ./ui
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        working-directory: ./ui
        run: npm run e2e:ci
        env:
          # Outputs information from webservers started in the background by
          # Playwright. Useful for understanding if something failing there
          # breaks the tests.
          DEBUG: pw:webserver
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            ui/e2e/playwright-report/
            ui/e2e/test-results/
      - name: Create tarballs of all packages
        run: cd ./ui && npm pack -ws
      - name: Replace Perses dependencies in examples folder with built packages
        run: for example in ./examples/*/; do (cd "$example"; npm install ../../ui/perses-dev-*.tgz); done
      - name: Verify all examples build successfully
        run: cd ./examples && ./test.sh
